USE rhodes_dwh;

CREATE OR REPLACE TABLE "RHODES_DWH"."RAW"."HOMEBUILDER_SALES" ( Contract_ID VARCHAR , Community VARCHAR , City VARCHAR , Region VARCHAR , Plan_Name VARCHAR , Sqft NUMBER(38, 0) , Bedrooms NUMBER(38, 0) , Bathrooms NUMBER(38, 1) , Base_Price NUMBER(38, 0) , Upgrade_Amount NUMBER(38, 0) , Incentive_Amount NUMBER(38, 0) , Contract_Price NUMBER(38, 0) , Contract_Date DATE , Close_Date DATE , Days_to_Close NUMBER(38, 0) , Status VARCHAR , Buyer_Source VARCHAR , Agent_Commission NUMBER(38, 1) , Loan_Type VARCHAR , Sales_Consultant VARCHAR ); 

CREATE OR REPLACE TEMP FILE FORMAT "RHODES_DWH"."RAW"."temp_file_format_2026-04-23T06:37:21.143Z"
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "RHODES_DWH"."RAW"."HOMEBUILDER_SALES" 
FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
	FROM '@"RHODES_DWH"."RAW"."RAW_STAGE"') 
FILES = ('Homebuilder_Sales.csv') 
FILE_FORMAT = '"RHODES_DWH"."RAW"."temp_file_format_2026-04-23T06:37:21.143Z"' 
ON_ERROR=ABORT_STATEMENT; 


CREATE OR REPLACE TABLE "RHODES_DWH"."RAW"."REGIONAL_MANAGER_LOOKUP" ( Region VARCHAR , Regional_Manager VARCHAR , Sales_Target_Units NUMBER(38, 0) , Margin_Target_Pct NUMBER(38, 2) ); 

CREATE OR REPLACE TEMP FILE FORMAT "RHODES_DWH"."RAW"."temp_file_format_2026-04-23T06:39:48.767Z"
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "RHODES_DWH"."RAW"."REGIONAL_MANAGER_LOOKUP" 
FROM (SELECT $1, $2, $3, $4
	FROM '@"RHODES_DWH"."RAW"."RAW_STAGE"') 
FILES = ('Regional_Manager_Lookup.csv') 
FILE_FORMAT = '"RHODES_DWH"."RAW"."temp_file_format_2026-04-23T06:39:48.767Z"' 
ON_ERROR=ABORT_STATEMENT; 

SELECT COUNT(*) FROM RAW.HOMEBUILDER_SALES;
SELECT COUNT(*) FROM RAW.REGIONAL_MANAGER_LOOKUP;

SELECT * FROM RAW.HOMEBUILDER_SALES LIMIT 700;
SELECT * FROM RAW.REGIONAL_MANAGER_LOOKUP;

